# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gui.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_YONGATEK(object):
    def setupUi(self, YONGATEK):
        YONGATEK.setObjectName("YONGATEK")
        YONGATEK.resize(1108, 733)
        YONGATEK.setMinimumSize(QtCore.QSize(1108, 733))
        YONGATEK.setMaximumSize(QtCore.QSize(1108, 733))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/icons/logo.svg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        YONGATEK.setWindowIcon(icon)
        self.function = QtWidgets.QTabWidget(YONGATEK)
        self.function.setGeometry(QtCore.QRect(20, 10, 1081, 711))
        self.function.setInputMethodHints(QtCore.Qt.ImhNone)
        self.function.setObjectName("function")
        self.menu = QtWidgets.QWidget()
        self.menu.setObjectName("menu")
        self.logo = QtWidgets.QLabel(self.menu)
        self.logo.setGeometry(QtCore.QRect(30, 0, 751, 551))
        self.logo.setStyleSheet("image: url(:/icons/icons/logo.svg)")
        self.logo.setText("")
        self.logo.setAlignment(QtCore.Qt.AlignCenter)
        self.logo.setObjectName("logo")
        self.rgb_btn = QtWidgets.QPushButton(self.menu)
        self.rgb_btn.setGeometry(QtCore.QRect(870, 80, 161, 61))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/icons/Actions-go-next-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.rgb_btn.setIcon(icon1)
        self.rgb_btn.setIconSize(QtCore.QSize(50, 50))
        self.rgb_btn.setObjectName("rgb_btn")
        self.shift_btn = QtWidgets.QPushButton(self.menu)
        self.shift_btn.setGeometry(QtCore.QRect(870, 150, 161, 61))
        self.shift_btn.setIcon(icon1)
        self.shift_btn.setIconSize(QtCore.QSize(50, 50))
        self.shift_btn.setObjectName("shift_btn")
        self.gray_btn = QtWidgets.QPushButton(self.menu)
        self.gray_btn.setGeometry(QtCore.QRect(870, 220, 161, 61))
        self.gray_btn.setIcon(icon1)
        self.gray_btn.setIconSize(QtCore.QSize(50, 50))
        self.gray_btn.setObjectName("gray_btn")
        self.YCbCr_btn = QtWidgets.QPushButton(self.menu)
        self.YCbCr_btn.setGeometry(QtCore.QRect(870, 290, 161, 61))
        self.YCbCr_btn.setIcon(icon1)
        self.YCbCr_btn.setIconSize(QtCore.QSize(50, 50))
        self.YCbCr_btn.setObjectName("YCbCr_btn")
        self.BIN2HEX_btn = QtWidgets.QPushButton(self.menu)
        self.BIN2HEX_btn.setGeometry(QtCore.QRect(870, 360, 161, 61))
        self.BIN2HEX_btn.setIcon(icon1)
        self.BIN2HEX_btn.setIconSize(QtCore.QSize(50, 50))
        self.BIN2HEX_btn.setObjectName("BIN2HEX_btn")
        self.DEC2BIN_btn = QtWidgets.QPushButton(self.menu)
        self.DEC2BIN_btn.setGeometry(QtCore.QRect(870, 430, 161, 61))
        self.DEC2BIN_btn.setIcon(icon1)
        self.DEC2BIN_btn.setIconSize(QtCore.QSize(50, 50))
        self.DEC2BIN_btn.setObjectName("DEC2BIN_btn")
        self.DEC2HEX_btn = QtWidgets.QPushButton(self.menu)
        self.DEC2HEX_btn.setGeometry(QtCore.QRect(870, 500, 161, 61))
        self.DEC2HEX_btn.setIcon(icon1)
        self.DEC2HEX_btn.setIconSize(QtCore.QSize(50, 50))
        self.DEC2HEX_btn.setObjectName("DEC2HEX_btn")
        self.function.addTab(self.menu, "")
        self.tab1 = QtWidgets.QWidget()
        self.tab1.setObjectName("tab1")
        self.open_image = QtWidgets.QPushButton(self.tab1)
        self.open_image.setGeometry(QtCore.QRect(750, 40, 141, 111))
        self.open_image.setStyleSheet("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/icons/My-Pictures-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_image.setIcon(icon2)
        self.open_image.setIconSize(QtCore.QSize(50, 50))
        self.open_image.setObjectName("open_image")
        self.cvt_bn = QtWidgets.QPushButton(self.tab1)
        self.cvt_bn.setGeometry(QtCore.QRect(740, 200, 101, 41))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/icons/document-add-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.cvt_bn.setIcon(icon3)
        self.cvt_bn.setIconSize(QtCore.QSize(25, 25))
        self.cvt_bn.setObjectName("cvt_bn")
        self.cvt_hexa = QtWidgets.QPushButton(self.tab1)
        self.cvt_hexa.setGeometry(QtCore.QRect(740, 260, 101, 41))
        self.cvt_hexa.setIcon(icon3)
        self.cvt_hexa.setIconSize(QtCore.QSize(25, 25))
        self.cvt_hexa.setObjectName("cvt_hexa")
        self.frame = QtWidgets.QFrame(self.tab1)
        self.frame.setGeometry(QtCore.QRect(60, 40, 661, 531))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.lbl_img = QtWidgets.QLabel(self.frame)
        self.lbl_img.setGeometry(QtCore.QRect(0, 0, 661, 531))
        self.lbl_img.setMinimumSize(QtCore.QSize(661, 531))
        self.lbl_img.setMaximumSize(QtCore.QSize(661, 531))
        font = QtGui.QFont()
        font.setKerning(True)
        self.lbl_img.setFont(font)
        self.lbl_img.setText("")
        self.lbl_img.setScaledContents(False)
        self.lbl_img.setAlignment(QtCore.Qt.AlignCenter)
        self.lbl_img.setObjectName("lbl_img")
        self.lbl_res = QtWidgets.QLabel(self.tab1)
        self.lbl_res.setGeometry(QtCore.QRect(60, 600, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_res.setFont(font)
        self.lbl_res.setText("")
        self.lbl_res.setObjectName("lbl_res")
        self.label = QtWidgets.QLabel(self.tab1)
        self.label.setGeometry(QtCore.QRect(900, 40, 111, 17))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.r_lbl = QtWidgets.QLabel(self.tab1)
        self.r_lbl.setGeometry(QtCore.QRect(900, 70, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.r_lbl.setFont(font)
        self.r_lbl.setObjectName("r_lbl")
        self.b_lbl = QtWidgets.QLabel(self.tab1)
        self.b_lbl.setGeometry(QtCore.QRect(900, 130, 21, 21))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.b_lbl.setFont(font)
        self.b_lbl.setObjectName("b_lbl")
        self.g_lbl = QtWidgets.QLabel(self.tab1)
        self.g_lbl.setGeometry(QtCore.QRect(900, 100, 21, 17))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.g_lbl.setFont(font)
        self.g_lbl.setObjectName("g_lbl")
        self.r_line = QtWidgets.QLineEdit(self.tab1)
        self.r_line.setGeometry(QtCore.QRect(930, 70, 115, 25))
        self.r_line.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.r_line.setObjectName("r_line")
        self.g_line = QtWidgets.QLineEdit(self.tab1)
        self.g_line.setGeometry(QtCore.QRect(930, 100, 115, 25))
        self.g_line.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.g_line.setObjectName("g_line")
        self.b_line = QtWidgets.QLineEdit(self.tab1)
        self.b_line.setGeometry(QtCore.QRect(930, 130, 115, 25))
        self.b_line.setInputMethodHints(QtCore.Qt.ImhPreferNumbers)
        self.b_line.setObjectName("b_line")
        self.label_2 = QtWidgets.QLabel(self.tab1)
        self.label_2.setGeometry(QtCore.QRect(740, 360, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_2.setFont(font)
        self.label_2.setFrameShape(QtWidgets.QFrame.Box)
        self.label_2.setObjectName("label_2")
        self.set_row = QtWidgets.QLineEdit(self.tab1)
        self.set_row.setGeometry(QtCore.QRect(740, 390, 321, 31))
        self.set_row.setObjectName("set_row")
        self.bin_zero_btn = QtWidgets.QPushButton(self.tab1)
        self.bin_zero_btn.setGeometry(QtCore.QRect(740, 430, 101, 41))
        self.bin_zero_btn.setIcon(icon3)
        self.bin_zero_btn.setIconSize(QtCore.QSize(25, 25))
        self.bin_zero_btn.setObjectName("bin_zero_btn")
        self.hex_zero_btn = QtWidgets.QPushButton(self.tab1)
        self.hex_zero_btn.setGeometry(QtCore.QRect(740, 490, 101, 41))
        self.hex_zero_btn.setIcon(icon3)
        self.hex_zero_btn.setIconSize(QtCore.QSize(25, 25))
        self.hex_zero_btn.setObjectName("hex_zero_btn")
        self.cvt_bn_coe = QtWidgets.QPushButton(self.tab1)
        self.cvt_bn_coe.setGeometry(QtCore.QRect(850, 200, 101, 41))
        self.cvt_bn_coe.setIcon(icon3)
        self.cvt_bn_coe.setIconSize(QtCore.QSize(25, 25))
        self.cvt_bn_coe.setObjectName("cvt_bn_coe")
        self.cvt_hexa_coe = QtWidgets.QPushButton(self.tab1)
        self.cvt_hexa_coe.setGeometry(QtCore.QRect(850, 260, 101, 41))
        self.cvt_hexa_coe.setIcon(icon3)
        self.cvt_hexa_coe.setIconSize(QtCore.QSize(25, 25))
        self.cvt_hexa_coe.setObjectName("cvt_hexa_coe")
        self.cvt_bn_mif = QtWidgets.QPushButton(self.tab1)
        self.cvt_bn_mif.setGeometry(QtCore.QRect(960, 200, 101, 41))
        self.cvt_bn_mif.setIcon(icon3)
        self.cvt_bn_mif.setIconSize(QtCore.QSize(25, 25))
        self.cvt_bn_mif.setObjectName("cvt_bn_mif")
        self.cvt_hex_mif = QtWidgets.QPushButton(self.tab1)
        self.cvt_hex_mif.setGeometry(QtCore.QRect(960, 260, 101, 41))
        self.cvt_hex_mif.setIcon(icon3)
        self.cvt_hex_mif.setIconSize(QtCore.QSize(25, 25))
        self.cvt_hex_mif.setObjectName("cvt_hex_mif")
        self.line = QtWidgets.QFrame(self.tab1)
        self.line.setGeometry(QtCore.QRect(740, 240, 331, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_3 = QtWidgets.QLabel(self.tab1)
        self.label_3.setGeometry(QtCore.QRect(740, 170, 311, 21))
        self.label_3.setObjectName("label_3")
        self.bin_zero_btn_coe = QtWidgets.QPushButton(self.tab1)
        self.bin_zero_btn_coe.setGeometry(QtCore.QRect(850, 430, 101, 41))
        self.bin_zero_btn_coe.setIcon(icon3)
        self.bin_zero_btn_coe.setIconSize(QtCore.QSize(25, 25))
        self.bin_zero_btn_coe.setObjectName("bin_zero_btn_coe")
        self.bin_zero_btn_mif = QtWidgets.QPushButton(self.tab1)
        self.bin_zero_btn_mif.setGeometry(QtCore.QRect(960, 430, 101, 41))
        self.bin_zero_btn_mif.setIcon(icon3)
        self.bin_zero_btn_mif.setIconSize(QtCore.QSize(25, 25))
        self.bin_zero_btn_mif.setObjectName("bin_zero_btn_mif")
        self.hex_zero_btn_coe = QtWidgets.QPushButton(self.tab1)
        self.hex_zero_btn_coe.setGeometry(QtCore.QRect(850, 490, 101, 41))
        self.hex_zero_btn_coe.setIcon(icon3)
        self.hex_zero_btn_coe.setIconSize(QtCore.QSize(25, 25))
        self.hex_zero_btn_coe.setObjectName("hex_zero_btn_coe")
        self.hex_zero_btn_mif = QtWidgets.QPushButton(self.tab1)
        self.hex_zero_btn_mif.setGeometry(QtCore.QRect(960, 490, 101, 41))
        self.hex_zero_btn_mif.setIcon(icon3)
        self.hex_zero_btn_mif.setIconSize(QtCore.QSize(25, 25))
        self.hex_zero_btn_mif.setObjectName("hex_zero_btn_mif")
        self.line_2 = QtWidgets.QFrame(self.tab1)
        self.line_2.setGeometry(QtCore.QRect(730, 470, 331, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line_3 = QtWidgets.QFrame(self.tab1)
        self.line_3.setGeometry(QtCore.QRect(720, 305, 361, 21))
        self.line_3.setLineWidth(3)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_4 = QtWidgets.QLabel(self.tab1)
        self.label_4.setGeometry(QtCore.QRect(740, 330, 311, 21))
        self.label_4.setObjectName("label_4")
        self.function.addTab(self.tab1, "")
        self.tab2 = QtWidgets.QWidget()
        self.tab2.setObjectName("tab2")
        self.layoutWidget = QtWidgets.QWidget(self.tab2)
        self.layoutWidget.setGeometry(QtCore.QRect(220, 60, 621, 61))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.shft_input = QtWidgets.QLineEdit(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shft_input.sizePolicy().hasHeightForWidth())
        self.shft_input.setSizePolicy(sizePolicy)
        self.shft_input.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.shft_input.setInputMask("")
        self.shft_input.setAlignment(QtCore.Qt.AlignCenter)
        self.shft_input.setObjectName("shft_input")
        self.horizontalLayout_2.addWidget(self.shft_input)
        self.shw_btn = QtWidgets.QPushButton(self.layoutWidget)
        self.shw_btn.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.shw_btn.sizePolicy().hasHeightForWidth())
        self.shw_btn.setSizePolicy(sizePolicy)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/icons/document-arrow-down-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.shw_btn.setIcon(icon4)
        self.shw_btn.setIconSize(QtCore.QSize(50, 50))
        self.shw_btn.setObjectName("shw_btn")
        self.horizontalLayout_2.addWidget(self.shw_btn)
        self.clr_btn = QtWidgets.QPushButton(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.clr_btn.sizePolicy().hasHeightForWidth())
        self.clr_btn.setSizePolicy(sizePolicy)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/icons/icons/Actions-edit-clear-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.clr_btn.setIcon(icon5)
        self.clr_btn.setIconSize(QtCore.QSize(50, 50))
        self.clr_btn.setObjectName("clr_btn")
        self.horizontalLayout_2.addWidget(self.clr_btn)
        self.textedit = QtWidgets.QTextEdit(self.tab2)
        self.textedit.setEnabled(True)
        self.textedit.setGeometry(QtCore.QRect(220, 120, 621, 471))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.textedit.setFont(font)
        self.textedit.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.textedit.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.textedit.setLineWidth(-7)
        self.textedit.setMidLineWidth(1)
        self.textedit.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.textedit.setObjectName("textedit")
        self.function.addTab(self.tab2, "")
        self.tab3 = QtWidgets.QWidget()
        self.tab3.setObjectName("tab3")
        self.line_4 = QtWidgets.QFrame(self.tab3)
        self.line_4.setGeometry(QtCore.QRect(740, 270, 331, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.cvt_hexa_coe_2 = QtWidgets.QPushButton(self.tab3)
        self.cvt_hexa_coe_2.setGeometry(QtCore.QRect(850, 290, 101, 41))
        self.cvt_hexa_coe_2.setIcon(icon3)
        self.cvt_hexa_coe_2.setIconSize(QtCore.QSize(25, 25))
        self.cvt_hexa_coe_2.setObjectName("cvt_hexa_coe_2")
        self.label_5 = QtWidgets.QLabel(self.tab3)
        self.label_5.setGeometry(QtCore.QRect(740, 390, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_5.setFont(font)
        self.label_5.setFrameShape(QtWidgets.QFrame.Box)
        self.label_5.setObjectName("label_5")
        self.line_5 = QtWidgets.QFrame(self.tab3)
        self.line_5.setGeometry(QtCore.QRect(730, 500, 331, 16))
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.cvt_hex_mif_2 = QtWidgets.QPushButton(self.tab3)
        self.cvt_hex_mif_2.setGeometry(QtCore.QRect(960, 290, 101, 41))
        self.cvt_hex_mif_2.setIcon(icon3)
        self.cvt_hex_mif_2.setIconSize(QtCore.QSize(25, 25))
        self.cvt_hex_mif_2.setObjectName("cvt_hex_mif_2")
        self.open_image_2 = QtWidgets.QPushButton(self.tab3)
        self.open_image_2.setGeometry(QtCore.QRect(790, 80, 191, 91))
        self.open_image_2.setMouseTracking(False)
        self.open_image_2.setStyleSheet("")
        self.open_image_2.setIcon(icon2)
        self.open_image_2.setIconSize(QtCore.QSize(50, 50))
        self.open_image_2.setObjectName("open_image_2")
        self.set_row_2 = QtWidgets.QLineEdit(self.tab3)
        self.set_row_2.setGeometry(QtCore.QRect(740, 420, 321, 31))
        self.set_row_2.setObjectName("set_row_2")
        self.cvt_hexa_2 = QtWidgets.QPushButton(self.tab3)
        self.cvt_hexa_2.setGeometry(QtCore.QRect(740, 290, 101, 41))
        self.cvt_hexa_2.setIcon(icon3)
        self.cvt_hexa_2.setIconSize(QtCore.QSize(25, 25))
        self.cvt_hexa_2.setObjectName("cvt_hexa_2")
        self.label_6 = QtWidgets.QLabel(self.tab3)
        self.label_6.setGeometry(QtCore.QRect(740, 200, 311, 21))
        self.label_6.setObjectName("label_6")
        self.lbl_img_2 = QtWidgets.QLabel(self.tab3)
        self.lbl_img_2.setGeometry(QtCore.QRect(30, 220, 661, 531))
        self.lbl_img_2.setMinimumSize(QtCore.QSize(661, 531))
        self.lbl_img_2.setMaximumSize(QtCore.QSize(661, 531))
        font = QtGui.QFont()
        font.setKerning(True)
        self.lbl_img_2.setFont(font)
        self.lbl_img_2.setText("")
        self.lbl_img_2.setObjectName("lbl_img_2")
        self.cvt_bn_coe_2 = QtWidgets.QPushButton(self.tab3)
        self.cvt_bn_coe_2.setGeometry(QtCore.QRect(850, 230, 101, 41))
        self.cvt_bn_coe_2.setIcon(icon3)
        self.cvt_bn_coe_2.setIconSize(QtCore.QSize(25, 25))
        self.cvt_bn_coe_2.setObjectName("cvt_bn_coe_2")
        self.bin_zero_btn_mif_2 = QtWidgets.QPushButton(self.tab3)
        self.bin_zero_btn_mif_2.setGeometry(QtCore.QRect(960, 460, 101, 41))
        self.bin_zero_btn_mif_2.setIcon(icon3)
        self.bin_zero_btn_mif_2.setIconSize(QtCore.QSize(25, 25))
        self.bin_zero_btn_mif_2.setObjectName("bin_zero_btn_mif_2")
        self.cvt_bn_2 = QtWidgets.QPushButton(self.tab3)
        self.cvt_bn_2.setGeometry(QtCore.QRect(740, 230, 101, 41))
        self.cvt_bn_2.setIcon(icon3)
        self.cvt_bn_2.setIconSize(QtCore.QSize(25, 25))
        self.cvt_bn_2.setObjectName("cvt_bn_2")
        self.hex_zero_btn_mif_2 = QtWidgets.QPushButton(self.tab3)
        self.hex_zero_btn_mif_2.setGeometry(QtCore.QRect(960, 520, 101, 41))
        self.hex_zero_btn_mif_2.setIcon(icon3)
        self.hex_zero_btn_mif_2.setIconSize(QtCore.QSize(25, 25))
        self.hex_zero_btn_mif_2.setObjectName("hex_zero_btn_mif_2")
        self.bin_zero_btn_2 = QtWidgets.QPushButton(self.tab3)
        self.bin_zero_btn_2.setGeometry(QtCore.QRect(740, 460, 101, 41))
        self.bin_zero_btn_2.setIcon(icon3)
        self.bin_zero_btn_2.setIconSize(QtCore.QSize(25, 25))
        self.bin_zero_btn_2.setObjectName("bin_zero_btn_2")
        self.bin_zero_btn_coe_2 = QtWidgets.QPushButton(self.tab3)
        self.bin_zero_btn_coe_2.setGeometry(QtCore.QRect(850, 460, 101, 41))
        self.bin_zero_btn_coe_2.setIcon(icon3)
        self.bin_zero_btn_coe_2.setIconSize(QtCore.QSize(25, 25))
        self.bin_zero_btn_coe_2.setObjectName("bin_zero_btn_coe_2")
        self.label_7 = QtWidgets.QLabel(self.tab3)
        self.label_7.setGeometry(QtCore.QRect(740, 360, 311, 21))
        self.label_7.setObjectName("label_7")
        self.line_6 = QtWidgets.QFrame(self.tab3)
        self.line_6.setGeometry(QtCore.QRect(720, 335, 361, 21))
        self.line_6.setLineWidth(3)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.cvt_bn_mif_2 = QtWidgets.QPushButton(self.tab3)
        self.cvt_bn_mif_2.setGeometry(QtCore.QRect(960, 230, 101, 41))
        self.cvt_bn_mif_2.setIcon(icon3)
        self.cvt_bn_mif_2.setIconSize(QtCore.QSize(25, 25))
        self.cvt_bn_mif_2.setObjectName("cvt_bn_mif_2")
        self.hex_zero_btn_2 = QtWidgets.QPushButton(self.tab3)
        self.hex_zero_btn_2.setGeometry(QtCore.QRect(740, 520, 101, 41))
        self.hex_zero_btn_2.setIcon(icon3)
        self.hex_zero_btn_2.setIconSize(QtCore.QSize(25, 25))
        self.hex_zero_btn_2.setObjectName("hex_zero_btn_2")
        self.hex_zero_btn_coe_2 = QtWidgets.QPushButton(self.tab3)
        self.hex_zero_btn_coe_2.setGeometry(QtCore.QRect(850, 520, 101, 41))
        self.hex_zero_btn_coe_2.setIcon(icon3)
        self.hex_zero_btn_coe_2.setIconSize(QtCore.QSize(25, 25))
        self.hex_zero_btn_coe_2.setObjectName("hex_zero_btn_coe_2")
        self.label_8 = QtWidgets.QLabel(self.tab3)
        self.label_8.setGeometry(QtCore.QRect(130, 0, 721, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.lbl_res_2 = QtWidgets.QLabel(self.tab3)
        self.lbl_res_2.setGeometry(QtCore.QRect(60, 590, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_res_2.setFont(font)
        self.lbl_res_2.setText("")
        self.lbl_res_2.setObjectName("lbl_res_2")
        self.frame_2 = QtWidgets.QFrame(self.tab3)
        self.frame_2.setGeometry(QtCore.QRect(40, 40, 661, 531))
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.lbl_img_3 = QtWidgets.QLabel(self.frame_2)
        self.lbl_img_3.setGeometry(QtCore.QRect(0, 0, 661, 531))
        self.lbl_img_3.setMinimumSize(QtCore.QSize(661, 531))
        self.lbl_img_3.setMaximumSize(QtCore.QSize(661, 531))
        font = QtGui.QFont()
        font.setKerning(True)
        self.lbl_img_3.setFont(font)
        self.lbl_img_3.setText("")
        self.lbl_img_3.setObjectName("lbl_img_3")
        self.function.addTab(self.tab3, "")
        self.tab4 = QtWidgets.QWidget()
        self.tab4.setObjectName("tab4")
        self.open_image_ycbcr = QtWidgets.QPushButton(self.tab4)
        self.open_image_ycbcr.setGeometry(QtCore.QRect(780, 20, 191, 71))
        self.open_image_ycbcr.setMouseTracking(False)
        self.open_image_ycbcr.setStyleSheet("")
        self.open_image_ycbcr.setIcon(icon2)
        self.open_image_ycbcr.setIconSize(QtCore.QSize(50, 50))
        self.open_image_ycbcr.setObjectName("open_image_ycbcr")
        self.lbl_img_7 = QtWidgets.QLabel(self.tab4)
        self.lbl_img_7.setGeometry(QtCore.QRect(20, 250, 661, 531))
        self.lbl_img_7.setMinimumSize(QtCore.QSize(661, 531))
        self.lbl_img_7.setMaximumSize(QtCore.QSize(661, 531))
        font = QtGui.QFont()
        font.setKerning(True)
        self.lbl_img_7.setFont(font)
        self.lbl_img_7.setText("")
        self.lbl_img_7.setObjectName("lbl_img_7")
        self.frame_5 = QtWidgets.QFrame(self.tab4)
        self.frame_5.setGeometry(QtCore.QRect(30, 40, 661, 531))
        self.frame_5.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.lbl_img_8 = QtWidgets.QLabel(self.frame_5)
        self.lbl_img_8.setGeometry(QtCore.QRect(0, 0, 661, 531))
        self.lbl_img_8.setMinimumSize(QtCore.QSize(661, 531))
        self.lbl_img_8.setMaximumSize(QtCore.QSize(661, 531))
        font = QtGui.QFont()
        font.setKerning(True)
        self.lbl_img_8.setFont(font)
        self.lbl_img_8.setText("")
        self.lbl_img_8.setObjectName("lbl_img_8")
        self.lbl_res_3 = QtWidgets.QLabel(self.tab4)
        self.lbl_res_3.setGeometry(QtCore.QRect(50, 600, 371, 31))
        font = QtGui.QFont()
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_res_3.setFont(font)
        self.lbl_res_3.setText("")
        self.lbl_res_3.setObjectName("lbl_res_3")
        self.toolBox = QtWidgets.QToolBox(self.tab4)
        self.toolBox.setGeometry(QtCore.QRect(710, 110, 351, 541))
        self.toolBox.setObjectName("toolBox")
        self.page = QtWidgets.QWidget()
        self.page.setGeometry(QtCore.QRect(0, 0, 98, 28))
        self.page.setObjectName("page")
        self.cvt_hex_mif_3 = QtWidgets.QPushButton(self.page)
        self.cvt_hex_mif_3.setGeometry(QtCore.QRect(230, 70, 101, 41))
        self.cvt_hex_mif_3.setIcon(icon3)
        self.cvt_hex_mif_3.setIconSize(QtCore.QSize(25, 25))
        self.cvt_hex_mif_3.setObjectName("cvt_hex_mif_3")
        self.cvt_bn_3 = QtWidgets.QPushButton(self.page)
        self.cvt_bn_3.setGeometry(QtCore.QRect(10, 10, 101, 41))
        self.cvt_bn_3.setIcon(icon3)
        self.cvt_bn_3.setIconSize(QtCore.QSize(25, 25))
        self.cvt_bn_3.setObjectName("cvt_bn_3")
        self.line_7 = QtWidgets.QFrame(self.page)
        self.line_7.setGeometry(QtCore.QRect(10, 50, 331, 16))
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.cvt_hexa_3 = QtWidgets.QPushButton(self.page)
        self.cvt_hexa_3.setGeometry(QtCore.QRect(10, 70, 101, 41))
        self.cvt_hexa_3.setIcon(icon3)
        self.cvt_hexa_3.setIconSize(QtCore.QSize(25, 25))
        self.cvt_hexa_3.setObjectName("cvt_hexa_3")
        self.cvt_bn_mif_3 = QtWidgets.QPushButton(self.page)
        self.cvt_bn_mif_3.setGeometry(QtCore.QRect(230, 10, 101, 41))
        self.cvt_bn_mif_3.setIcon(icon3)
        self.cvt_bn_mif_3.setIconSize(QtCore.QSize(25, 25))
        self.cvt_bn_mif_3.setObjectName("cvt_bn_mif_3")
        self.cvt_hexa_coe_3 = QtWidgets.QPushButton(self.page)
        self.cvt_hexa_coe_3.setGeometry(QtCore.QRect(120, 70, 101, 41))
        self.cvt_hexa_coe_3.setIcon(icon3)
        self.cvt_hexa_coe_3.setIconSize(QtCore.QSize(25, 25))
        self.cvt_hexa_coe_3.setObjectName("cvt_hexa_coe_3")
        self.cvt_bn_coe_3 = QtWidgets.QPushButton(self.page)
        self.cvt_bn_coe_3.setGeometry(QtCore.QRect(120, 10, 101, 41))
        self.cvt_bn_coe_3.setIcon(icon3)
        self.cvt_bn_coe_3.setIconSize(QtCore.QSize(25, 25))
        self.cvt_bn_coe_3.setObjectName("cvt_bn_coe_3")
        self.hex_zero_btn_mif_3 = QtWidgets.QPushButton(self.page)
        self.hex_zero_btn_mif_3.setGeometry(QtCore.QRect(230, 310, 101, 41))
        self.hex_zero_btn_mif_3.setIcon(icon3)
        self.hex_zero_btn_mif_3.setIconSize(QtCore.QSize(25, 25))
        self.hex_zero_btn_mif_3.setObjectName("hex_zero_btn_mif_3")
        self.line_9 = QtWidgets.QFrame(self.page)
        self.line_9.setGeometry(QtCore.QRect(-10, 125, 361, 21))
        self.line_9.setLineWidth(3)
        self.line_9.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_9.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_9.setObjectName("line_9")
        self.set_row_3 = QtWidgets.QLineEdit(self.page)
        self.set_row_3.setGeometry(QtCore.QRect(10, 210, 321, 31))
        self.set_row_3.setObjectName("set_row_3")
        self.label_17 = QtWidgets.QLabel(self.page)
        self.label_17.setGeometry(QtCore.QRect(10, 180, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_17.setFont(font)
        self.label_17.setFrameShape(QtWidgets.QFrame.Box)
        self.label_17.setObjectName("label_17")
        self.bin_zero_btn_mif_3 = QtWidgets.QPushButton(self.page)
        self.bin_zero_btn_mif_3.setGeometry(QtCore.QRect(230, 250, 101, 41))
        self.bin_zero_btn_mif_3.setIcon(icon3)
        self.bin_zero_btn_mif_3.setIconSize(QtCore.QSize(25, 25))
        self.bin_zero_btn_mif_3.setObjectName("bin_zero_btn_mif_3")
        self.label_18 = QtWidgets.QLabel(self.page)
        self.label_18.setGeometry(QtCore.QRect(10, 150, 311, 21))
        self.label_18.setObjectName("label_18")
        self.bin_zero_btn_3 = QtWidgets.QPushButton(self.page)
        self.bin_zero_btn_3.setGeometry(QtCore.QRect(10, 250, 101, 41))
        self.bin_zero_btn_3.setIcon(icon3)
        self.bin_zero_btn_3.setIconSize(QtCore.QSize(25, 25))
        self.bin_zero_btn_3.setObjectName("bin_zero_btn_3")
        self.line_10 = QtWidgets.QFrame(self.page)
        self.line_10.setGeometry(QtCore.QRect(0, 290, 331, 16))
        self.line_10.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_10.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_10.setObjectName("line_10")
        self.hex_zero_btn_3 = QtWidgets.QPushButton(self.page)
        self.hex_zero_btn_3.setGeometry(QtCore.QRect(10, 310, 101, 41))
        self.hex_zero_btn_3.setIcon(icon3)
        self.hex_zero_btn_3.setIconSize(QtCore.QSize(25, 25))
        self.hex_zero_btn_3.setObjectName("hex_zero_btn_3")
        self.bin_zero_btn_coe_3 = QtWidgets.QPushButton(self.page)
        self.bin_zero_btn_coe_3.setGeometry(QtCore.QRect(120, 250, 101, 41))
        self.bin_zero_btn_coe_3.setIcon(icon3)
        self.bin_zero_btn_coe_3.setIconSize(QtCore.QSize(25, 25))
        self.bin_zero_btn_coe_3.setObjectName("bin_zero_btn_coe_3")
        self.hex_zero_btn_coe_3 = QtWidgets.QPushButton(self.page)
        self.hex_zero_btn_coe_3.setGeometry(QtCore.QRect(120, 310, 101, 41))
        self.hex_zero_btn_coe_3.setIcon(icon3)
        self.hex_zero_btn_coe_3.setIconSize(QtCore.QSize(25, 25))
        self.hex_zero_btn_coe_3.setObjectName("hex_zero_btn_coe_3")
        self.toolBox.addItem(self.page, "")
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setGeometry(QtCore.QRect(0, 0, 351, 479))
        self.page_2.setObjectName("page_2")
        self.line_11 = QtWidgets.QFrame(self.page_2)
        self.line_11.setGeometry(QtCore.QRect(-10, 125, 361, 21))
        self.line_11.setLineWidth(3)
        self.line_11.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_11.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_11.setObjectName("line_11")
        self.label_19 = QtWidgets.QLabel(self.page_2)
        self.label_19.setGeometry(QtCore.QRect(10, 180, 321, 31))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.label_19.setFont(font)
        self.label_19.setFrameShape(QtWidgets.QFrame.Box)
        self.label_19.setObjectName("label_19")
        self.set_row_4 = QtWidgets.QLineEdit(self.page_2)
        self.set_row_4.setGeometry(QtCore.QRect(10, 210, 321, 31))
        self.set_row_4.setObjectName("set_row_4")
        self.bin_zero_btn_mif_4 = QtWidgets.QPushButton(self.page_2)
        self.bin_zero_btn_mif_4.setGeometry(QtCore.QRect(230, 250, 101, 41))
        self.bin_zero_btn_mif_4.setIcon(icon3)
        self.bin_zero_btn_mif_4.setIconSize(QtCore.QSize(25, 25))
        self.bin_zero_btn_mif_4.setObjectName("bin_zero_btn_mif_4")
        self.label_20 = QtWidgets.QLabel(self.page_2)
        self.label_20.setGeometry(QtCore.QRect(10, 150, 311, 21))
        self.label_20.setObjectName("label_20")
        self.bin_zero_btn_4 = QtWidgets.QPushButton(self.page_2)
        self.bin_zero_btn_4.setGeometry(QtCore.QRect(10, 250, 101, 41))
        self.bin_zero_btn_4.setIcon(icon3)
        self.bin_zero_btn_4.setIconSize(QtCore.QSize(25, 25))
        self.bin_zero_btn_4.setObjectName("bin_zero_btn_4")
        self.line_12 = QtWidgets.QFrame(self.page_2)
        self.line_12.setGeometry(QtCore.QRect(0, 290, 331, 16))
        self.line_12.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_12.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_12.setObjectName("line_12")
        self.hex_zero_btn_4 = QtWidgets.QPushButton(self.page_2)
        self.hex_zero_btn_4.setGeometry(QtCore.QRect(10, 310, 101, 41))
        self.hex_zero_btn_4.setIcon(icon3)
        self.hex_zero_btn_4.setIconSize(QtCore.QSize(25, 25))
        self.hex_zero_btn_4.setObjectName("hex_zero_btn_4")
        self.bin_zero_btn_coe_4 = QtWidgets.QPushButton(self.page_2)
        self.bin_zero_btn_coe_4.setGeometry(QtCore.QRect(120, 250, 101, 41))
        self.bin_zero_btn_coe_4.setIcon(icon3)
        self.bin_zero_btn_coe_4.setIconSize(QtCore.QSize(25, 25))
        self.bin_zero_btn_coe_4.setObjectName("bin_zero_btn_coe_4")
        self.hex_zero_btn_mif_4 = QtWidgets.QPushButton(self.page_2)
        self.hex_zero_btn_mif_4.setGeometry(QtCore.QRect(230, 310, 101, 41))
        self.hex_zero_btn_mif_4.setIcon(icon3)
        self.hex_zero_btn_mif_4.setIconSize(QtCore.QSize(25, 25))
        self.hex_zero_btn_mif_4.setObjectName("hex_zero_btn_mif_4")
        self.hex_zero_btn_coe_4 = QtWidgets.QPushButton(self.page_2)
        self.hex_zero_btn_coe_4.setGeometry(QtCore.QRect(120, 310, 101, 41))
        self.hex_zero_btn_coe_4.setIcon(icon3)
        self.hex_zero_btn_coe_4.setIconSize(QtCore.QSize(25, 25))
        self.hex_zero_btn_coe_4.setObjectName("hex_zero_btn_coe_4")
        self.cvt_hexa_coe_4 = QtWidgets.QPushButton(self.page_2)
        self.cvt_hexa_coe_4.setGeometry(QtCore.QRect(120, 70, 101, 41))
        self.cvt_hexa_coe_4.setIcon(icon3)
        self.cvt_hexa_coe_4.setIconSize(QtCore.QSize(25, 25))
        self.cvt_hexa_coe_4.setObjectName("cvt_hexa_coe_4")
        self.cvt_hex_mif_4 = QtWidgets.QPushButton(self.page_2)
        self.cvt_hex_mif_4.setGeometry(QtCore.QRect(230, 70, 101, 41))
        self.cvt_hex_mif_4.setIcon(icon3)
        self.cvt_hex_mif_4.setIconSize(QtCore.QSize(25, 25))
        self.cvt_hex_mif_4.setObjectName("cvt_hex_mif_4")
        self.cvt_bn_coe_4 = QtWidgets.QPushButton(self.page_2)
        self.cvt_bn_coe_4.setGeometry(QtCore.QRect(120, 10, 101, 41))
        self.cvt_bn_coe_4.setIcon(icon3)
        self.cvt_bn_coe_4.setIconSize(QtCore.QSize(25, 25))
        self.cvt_bn_coe_4.setObjectName("cvt_bn_coe_4")
        self.cvt_hexa_4 = QtWidgets.QPushButton(self.page_2)
        self.cvt_hexa_4.setGeometry(QtCore.QRect(10, 70, 101, 41))
        self.cvt_hexa_4.setIcon(icon3)
        self.cvt_hexa_4.setIconSize(QtCore.QSize(25, 25))
        self.cvt_hexa_4.setObjectName("cvt_hexa_4")
        self.cvt_bn_mif_4 = QtWidgets.QPushButton(self.page_2)
        self.cvt_bn_mif_4.setGeometry(QtCore.QRect(230, 10, 101, 41))
        self.cvt_bn_mif_4.setIcon(icon3)
        self.cvt_bn_mif_4.setIconSize(QtCore.QSize(25, 25))
        self.cvt_bn_mif_4.setObjectName("cvt_bn_mif_4")
        self.cvt_bn_4 = QtWidgets.QPushButton(self.page_2)
        self.cvt_bn_4.setGeometry(QtCore.QRect(10, 10, 101, 41))
        self.cvt_bn_4.setIcon(icon3)
        self.cvt_bn_4.setIconSize(QtCore.QSize(25, 25))
        self.cvt_bn_4.setObjectName("cvt_bn_4")
        self.line_13 = QtWidgets.QFrame(self.page_2)
        self.line_13.setGeometry(QtCore.QRect(0, 50, 331, 16))
        self.line_13.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_13.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_13.setObjectName("line_13")
        self.toolBox.addItem(self.page_2, "")
        self.function.addTab(self.tab4, "")
        self.tab5 = QtWidgets.QWidget()
        self.tab5.setObjectName("tab5")
        self.RES_HEX = QtWidgets.QTextEdit(self.tab5)
        self.RES_HEX.setGeometry(QtCore.QRect(260, 230, 221, 41))
        self.RES_HEX.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.RES_HEX.setObjectName("RES_HEX")
        self.label_10 = QtWidgets.QLabel(self.tab5)
        self.label_10.setGeometry(QtCore.QRect(70, 230, 181, 51))
        self.label_10.setObjectName("label_10")
        self.lineEdit_BN_INPUT = QtWidgets.QLineEdit(self.tab5)
        self.lineEdit_BN_INPUT.setGeometry(QtCore.QRect(260, 180, 221, 41))
        self.lineEdit_BN_INPUT.setInputMethodHints(QtCore.Qt.ImhFormattedNumbersOnly|QtCore.Qt.ImhPreferNumbers)
        self.lineEdit_BN_INPUT.setObjectName("lineEdit_BN_INPUT")
        self.RES_BN = QtWidgets.QTextEdit(self.tab5)
        self.RES_BN.setGeometry(QtCore.QRect(720, 240, 221, 41))
        self.RES_BN.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.RES_BN.setObjectName("RES_BN")
        self.label_12 = QtWidgets.QLabel(self.tab5)
        self.label_12.setGeometry(QtCore.QRect(530, 170, 181, 51))
        self.label_12.setObjectName("label_12")
        self.label_11 = QtWidgets.QLabel(self.tab5)
        self.label_11.setGeometry(QtCore.QRect(570, 230, 131, 51))
        self.label_11.setObjectName("label_11")
        self.BTN_BN2HEX = QtWidgets.QPushButton(self.tab5)
        self.BTN_BN2HEX.setGeometry(QtCore.QRect(290, 280, 171, 91))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/icons/icons/Apps-Accessories-Media-Converter-icon.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.BTN_BN2HEX.setIcon(icon6)
        self.BTN_BN2HEX.setIconSize(QtCore.QSize(60, 60))
        self.BTN_BN2HEX.setObjectName("BTN_BN2HEX")
        self.label_9 = QtWidgets.QLabel(self.tab5)
        self.label_9.setGeometry(QtCore.QRect(120, 170, 131, 51))
        self.label_9.setObjectName("label_9")
        self.lineEdit_HEX_INPUT = QtWidgets.QLineEdit(self.tab5)
        self.lineEdit_HEX_INPUT.setGeometry(QtCore.QRect(720, 180, 221, 41))
        self.lineEdit_HEX_INPUT.setObjectName("lineEdit_HEX_INPUT")
        self.BTN_HEX2BN = QtWidgets.QPushButton(self.tab5)
        self.BTN_HEX2BN.setGeometry(QtCore.QRect(740, 290, 171, 91))
        self.BTN_HEX2BN.setIcon(icon6)
        self.BTN_HEX2BN.setIconSize(QtCore.QSize(60, 60))
        self.BTN_HEX2BN.setObjectName("BTN_HEX2BN")
        self.function.addTab(self.tab5, "")
        self.tab6 = QtWidgets.QWidget()
        self.tab6.setObjectName("tab6")
        self.lineEdit_DEC_INPUT = QtWidgets.QLineEdit(self.tab6)
        self.lineEdit_DEC_INPUT.setGeometry(QtCore.QRect(250, 180, 221, 41))
        self.lineEdit_DEC_INPUT.setObjectName("lineEdit_DEC_INPUT")
        self.lineEdit_BN_INPUT_2 = QtWidgets.QLineEdit(self.tab6)
        self.lineEdit_BN_INPUT_2.setGeometry(QtCore.QRect(710, 180, 221, 41))
        self.lineEdit_BN_INPUT_2.setObjectName("lineEdit_BN_INPUT_2")
        self.RES_DEC = QtWidgets.QTextEdit(self.tab6)
        self.RES_DEC.setGeometry(QtCore.QRect(710, 230, 221, 41))
        self.RES_DEC.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.RES_DEC.setObjectName("RES_DEC")
        self.RES_BN_2 = QtWidgets.QTextEdit(self.tab6)
        self.RES_BN_2.setGeometry(QtCore.QRect(250, 230, 221, 41))
        self.RES_BN_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.RES_BN_2.setObjectName("RES_BN_2")
        self.label_13 = QtWidgets.QLabel(self.tab6)
        self.label_13.setGeometry(QtCore.QRect(100, 170, 141, 51))
        self.label_13.setObjectName("label_13")
        self.BTN_DEC2BN = QtWidgets.QPushButton(self.tab6)
        self.BTN_DEC2BN.setGeometry(QtCore.QRect(270, 290, 181, 91))
        self.BTN_DEC2BN.setIcon(icon6)
        self.BTN_DEC2BN.setIconSize(QtCore.QSize(60, 60))
        self.BTN_DEC2BN.setObjectName("BTN_DEC2BN")
        self.label_16 = QtWidgets.QLabel(self.tab6)
        self.label_16.setGeometry(QtCore.QRect(110, 220, 131, 51))
        self.label_16.setObjectName("label_16")
        self.BTN_BN2DEC = QtWidgets.QPushButton(self.tab6)
        self.BTN_BN2DEC.setGeometry(QtCore.QRect(720, 290, 191, 91))
        self.BTN_BN2DEC.setIcon(icon6)
        self.BTN_BN2DEC.setIconSize(QtCore.QSize(60, 60))
        self.BTN_BN2DEC.setObjectName("BTN_BN2DEC")
        self.label_15 = QtWidgets.QLabel(self.tab6)
        self.label_15.setGeometry(QtCore.QRect(570, 220, 131, 51))
        self.label_15.setObjectName("label_15")
        self.label_14 = QtWidgets.QLabel(self.tab6)
        self.label_14.setGeometry(QtCore.QRect(570, 180, 131, 51))
        self.label_14.setObjectName("label_14")
        self.function.addTab(self.tab6, "")
        self.tab7 = QtWidgets.QWidget()
        self.tab7.setObjectName("tab7")
        self.RES_DEC_2 = QtWidgets.QTextEdit(self.tab7)
        self.RES_DEC_2.setGeometry(QtCore.QRect(730, 250, 221, 41))
        self.RES_DEC_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.RES_DEC_2.setObjectName("RES_DEC_2")
        self.label_29 = QtWidgets.QLabel(self.tab7)
        self.label_29.setGeometry(QtCore.QRect(80, 240, 181, 51))
        self.label_29.setObjectName("label_29")
        self.lineEdit_HEX_INPUT_3 = QtWidgets.QLineEdit(self.tab7)
        self.lineEdit_HEX_INPUT_3.setGeometry(QtCore.QRect(730, 190, 221, 41))
        self.lineEdit_HEX_INPUT_3.setText("")
        self.lineEdit_HEX_INPUT_3.setObjectName("lineEdit_HEX_INPUT_3")
        self.label_26 = QtWidgets.QLabel(self.tab7)
        self.label_26.setGeometry(QtCore.QRect(130, 180, 131, 51))
        self.label_26.setObjectName("label_26")
        self.BTN_DEC2HEX = QtWidgets.QPushButton(self.tab7)
        self.BTN_DEC2HEX.setGeometry(QtCore.QRect(300, 310, 181, 91))
        self.BTN_DEC2HEX.setIcon(icon6)
        self.BTN_DEC2HEX.setIconSize(QtCore.QSize(60, 60))
        self.BTN_DEC2HEX.setObjectName("BTN_DEC2HEX")
        self.BTN_HEX2DEC = QtWidgets.QPushButton(self.tab7)
        self.BTN_HEX2DEC.setGeometry(QtCore.QRect(750, 310, 181, 91))
        self.BTN_HEX2DEC.setIcon(icon6)
        self.BTN_HEX2DEC.setIconSize(QtCore.QSize(60, 60))
        self.BTN_HEX2DEC.setObjectName("BTN_HEX2DEC")
        self.label_27 = QtWidgets.QLabel(self.tab7)
        self.label_27.setGeometry(QtCore.QRect(540, 180, 181, 51))
        self.label_27.setObjectName("label_27")
        self.RES_HEX_2 = QtWidgets.QTextEdit(self.tab7)
        self.RES_HEX_2.setGeometry(QtCore.QRect(270, 250, 221, 41))
        self.RES_HEX_2.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.RES_HEX_2.setObjectName("RES_HEX_2")
        self.lineEdit_DEC_INPUT_3 = QtWidgets.QLineEdit(self.tab7)
        self.lineEdit_DEC_INPUT_3.setGeometry(QtCore.QRect(270, 190, 221, 41))
        self.lineEdit_DEC_INPUT_3.setText("")
        self.lineEdit_DEC_INPUT_3.setObjectName("lineEdit_DEC_INPUT_3")
        self.label_28 = QtWidgets.QLabel(self.tab7)
        self.label_28.setGeometry(QtCore.QRect(570, 240, 141, 51))
        self.label_28.setObjectName("label_28")
        self.function.addTab(self.tab7, "")

        self.retranslateUi(YONGATEK)
        self.function.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(YONGATEK)

    def retranslateUi(self, YONGATEK):
        _translate = QtCore.QCoreApplication.translate
        YONGATEK.setWindowTitle(_translate("YONGATEK", "YONGATEK"))
        self.rgb_btn.setText(_translate("YONGATEK", "RGB"))
        self.shift_btn.setText(_translate("YONGATEK", "SHIFT"))
        self.gray_btn.setText(_translate("YONGATEK", "GRAY-S"))
        self.YCbCr_btn.setText(_translate("YONGATEK", "YCbCr"))
        self.BIN2HEX_btn.setText(_translate("YONGATEK", "BIN2HEX"))
        self.DEC2BIN_btn.setText(_translate("YONGATEK", "DEC2BIN"))
        self.DEC2HEX_btn.setText(_translate("YONGATEK", "DEC2HEX"))
        self.function.setTabText(self.function.indexOf(self.menu), _translate("YONGATEK", "Menu"))
        self.open_image.setToolTip(_translate("YONGATEK", "open image"))
        self.open_image.setText(_translate("YONGATEK", "Open Image"))
        self.cvt_bn.setToolTip(_translate("YONGATEK", "Convert rgb to binary format .dat file"))
        self.cvt_bn.setText(_translate("YONGATEK", " Binary.dat"))
        self.cvt_hexa.setToolTip(_translate("YONGATEK", "Convert rgb to hexadecimal format .dat file"))
        self.cvt_hexa.setText(_translate("YONGATEK", "Hex.dat"))
        self.label.setText(_translate("YONGATEK", "Bit Values :"))
        self.r_lbl.setText(_translate("YONGATEK", "R:"))
        self.b_lbl.setText(_translate("YONGATEK", "B:"))
        self.g_lbl.setText(_translate("YONGATEK", "G:"))
        self.label_2.setText(_translate("YONGATEK", "How Many Row Get Filled with Zeros :"))
        self.bin_zero_btn.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.bin_zero_btn.setText(_translate("YONGATEK", "binary.dat"))
        self.hex_zero_btn.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.hex_zero_btn.setText(_translate("YONGATEK", "hexa.dat"))
        self.cvt_bn_coe.setToolTip(_translate("YONGATEK", "Convert rgb to binary format .coe file"))
        self.cvt_bn_coe.setText(_translate("YONGATEK", " Binary.coe"))
        self.cvt_hexa_coe.setToolTip(_translate("YONGATEK", "Convert rgb to hexadecimal format .coe file"))
        self.cvt_hexa_coe.setText(_translate("YONGATEK", "Hex.coe"))
        self.cvt_bn_mif.setToolTip(_translate("YONGATEK", "Convert rgb to binary format .mif file"))
        self.cvt_bn_mif.setText(_translate("YONGATEK", "Binary.mif"))
        self.cvt_hex_mif.setToolTip(_translate("YONGATEK", "Convert rgb to hexadecimal format .mif file"))
        self.cvt_hex_mif.setText(_translate("YONGATEK", " Hex.mif"))
        self.label_3.setText(_translate("YONGATEK", "CONVERT TO :"))
        self.bin_zero_btn_coe.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.bin_zero_btn_coe.setText(_translate("YONGATEK", "binary.coe"))
        self.bin_zero_btn_mif.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.bin_zero_btn_mif.setText(_translate("YONGATEK", "binary.mif"))
        self.hex_zero_btn_coe.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.hex_zero_btn_coe.setText(_translate("YONGATEK", "hexa.coe"))
        self.hex_zero_btn_mif.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.hex_zero_btn_mif.setText(_translate("YONGATEK", "hexa.mif"))
        self.label_4.setText(_translate("YONGATEK", "FILL IN WITH ZEROS : "))
        self.function.setTabText(self.function.indexOf(self.tab1), _translate("YONGATEK", "RGB"))
        self.shft_input.setText(_translate("YONGATEK", "0."))
        self.shft_input.setPlaceholderText(_translate("YONGATEK", "Between 0 and 1"))
        self.shw_btn.setText(_translate("YONGATEK", "SHOW RESULT"))
        self.clr_btn.setText(_translate("YONGATEK", "Clear"))
        self.function.setTabText(self.function.indexOf(self.tab2), _translate("YONGATEK", "SHIFT"))
        self.cvt_hexa_coe_2.setToolTip(_translate("YONGATEK", "Convert hexadecimal format .coe file"))
        self.cvt_hexa_coe_2.setText(_translate("YONGATEK", "Hex.coe"))
        self.label_5.setText(_translate("YONGATEK", "How Many Row Get Filled with Zeros :"))
        self.cvt_hex_mif_2.setToolTip(_translate("YONGATEK", "Convert hexadecimal format .mif file"))
        self.cvt_hex_mif_2.setText(_translate("YONGATEK", " Hex.mif"))
        self.open_image_2.setText(_translate("YONGATEK", "Open Image"))
        self.cvt_hexa_2.setToolTip(_translate("YONGATEK", "Convert hexadecimal format .dat file"))
        self.cvt_hexa_2.setText(_translate("YONGATEK", "Hex.dat"))
        self.label_6.setText(_translate("YONGATEK", "CONVERT TO :"))
        self.cvt_bn_coe_2.setToolTip(_translate("YONGATEK", "Convert binary format .coe file"))
        self.cvt_bn_coe_2.setText(_translate("YONGATEK", " Binary.coe"))
        self.bin_zero_btn_mif_2.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.bin_zero_btn_mif_2.setText(_translate("YONGATEK", "binary.mif"))
        self.cvt_bn_2.setToolTip(_translate("YONGATEK", "Convert binary format .dat file"))
        self.cvt_bn_2.setText(_translate("YONGATEK", " Binary.dat"))
        self.hex_zero_btn_mif_2.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.hex_zero_btn_mif_2.setText(_translate("YONGATEK", "hexa.mif"))
        self.bin_zero_btn_2.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.bin_zero_btn_2.setText(_translate("YONGATEK", "binary.dat"))
        self.bin_zero_btn_coe_2.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.bin_zero_btn_coe_2.setText(_translate("YONGATEK", "binary.coe"))
        self.label_7.setText(_translate("YONGATEK", "FILL IN WITH ZEROS : "))
        self.cvt_bn_mif_2.setToolTip(_translate("YONGATEK", "Convert binary format .mif file"))
        self.cvt_bn_mif_2.setText(_translate("YONGATEK", "Binary.mif"))
        self.hex_zero_btn_2.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.hex_zero_btn_2.setText(_translate("YONGATEK", "hexa.dat"))
        self.hex_zero_btn_coe_2.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.hex_zero_btn_coe_2.setText(_translate("YONGATEK", "hexa.coe"))
        self.label_8.setText(_translate("YONGATEK", "For Gray Scale Image"))
        self.function.setTabText(self.function.indexOf(self.tab3), _translate("YONGATEK", "GRAY-S"))
        self.open_image_ycbcr.setText(_translate("YONGATEK", "Open Image"))
        self.cvt_hex_mif_3.setToolTip(_translate("YONGATEK", "Convert ycbcr to hexadecimal format .mif file"))
        self.cvt_hex_mif_3.setText(_translate("YONGATEK", " Hex.mif"))
        self.cvt_bn_3.setToolTip(_translate("YONGATEK", "Convert ycbcr to binary format .dat file"))
        self.cvt_bn_3.setText(_translate("YONGATEK", " Binary.dat"))
        self.cvt_hexa_3.setToolTip(_translate("YONGATEK", "Convert ycbcr to hexadecimal format .dat file"))
        self.cvt_hexa_3.setText(_translate("YONGATEK", "Hex.dat"))
        self.cvt_bn_mif_3.setToolTip(_translate("YONGATEK", "Convert ycbcr to binary format .mif file"))
        self.cvt_bn_mif_3.setText(_translate("YONGATEK", "Binary.mif"))
        self.cvt_hexa_coe_3.setToolTip(_translate("YONGATEK", "Convert ycbcr to hexadecimal format .coe file"))
        self.cvt_hexa_coe_3.setText(_translate("YONGATEK", "Hex.coe"))
        self.cvt_bn_coe_3.setToolTip(_translate("YONGATEK", "Convert ycbcr to binary format .coe file"))
        self.cvt_bn_coe_3.setText(_translate("YONGATEK", " Binary.coe"))
        self.hex_zero_btn_mif_3.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.hex_zero_btn_mif_3.setText(_translate("YONGATEK", "hexa.mif"))
        self.label_17.setText(_translate("YONGATEK", "How Many Row Get Filled with Zeros :"))
        self.bin_zero_btn_mif_3.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.bin_zero_btn_mif_3.setText(_translate("YONGATEK", "binary.mif"))
        self.label_18.setText(_translate("YONGATEK", "FILL IN WITH ZEROS : "))
        self.bin_zero_btn_3.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.bin_zero_btn_3.setText(_translate("YONGATEK", "binary.dat"))
        self.hex_zero_btn_3.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.hex_zero_btn_3.setText(_translate("YONGATEK", "hexa.dat"))
        self.bin_zero_btn_coe_3.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.bin_zero_btn_coe_3.setText(_translate("YONGATEK", "binary.coe"))
        self.hex_zero_btn_coe_3.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.hex_zero_btn_coe_3.setText(_translate("YONGATEK", "hexa.coe"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page), _translate("YONGATEK", "CONVERT RGB TO YCbCr 4.4.4 :"))
        self.label_19.setText(_translate("YONGATEK", "How Many Row Get Filled with Zeros :"))
        self.bin_zero_btn_mif_4.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.bin_zero_btn_mif_4.setText(_translate("YONGATEK", "binary.mif"))
        self.label_20.setText(_translate("YONGATEK", "FILL IN WITH ZEROS : "))
        self.bin_zero_btn_4.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.bin_zero_btn_4.setText(_translate("YONGATEK", "binary.dat"))
        self.hex_zero_btn_4.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.hex_zero_btn_4.setText(_translate("YONGATEK", "hexa.dat"))
        self.bin_zero_btn_coe_4.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.bin_zero_btn_coe_4.setText(_translate("YONGATEK", "binary.coe"))
        self.hex_zero_btn_mif_4.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.hex_zero_btn_mif_4.setText(_translate("YONGATEK", "hexa.mif"))
        self.hex_zero_btn_coe_4.setToolTip(_translate("YONGATEK", "get filled with zeros from the last line to the added line"))
        self.hex_zero_btn_coe_4.setText(_translate("YONGATEK", "hexa.coe"))
        self.cvt_hexa_coe_4.setToolTip(_translate("YONGATEK", "Convert ycbcr to hexadecimal format .coe file"))
        self.cvt_hexa_coe_4.setText(_translate("YONGATEK", "Hex.coe"))
        self.cvt_hex_mif_4.setToolTip(_translate("YONGATEK", "Convert ycbcr to hexadecimal format .mif file"))
        self.cvt_hex_mif_4.setText(_translate("YONGATEK", " Hex.mif"))
        self.cvt_bn_coe_4.setToolTip(_translate("YONGATEK", "Convert ycbcr to binary format .coe file"))
        self.cvt_bn_coe_4.setText(_translate("YONGATEK", " Binary.coe"))
        self.cvt_hexa_4.setToolTip(_translate("YONGATEK", "Convert ycbcr to hexadecimal format .dat file"))
        self.cvt_hexa_4.setText(_translate("YONGATEK", "Hex.dat"))
        self.cvt_bn_mif_4.setToolTip(_translate("YONGATEK", "Convert ycbcr to binary format .mif file"))
        self.cvt_bn_mif_4.setText(_translate("YONGATEK", "Binary.mif"))
        self.cvt_bn_4.setToolTip(_translate("YONGATEK", "Convert ycbcr to binary format .dat file"))
        self.cvt_bn_4.setText(_translate("YONGATEK", " Binary.dat"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.page_2), _translate("YONGATEK", "CONVERT RGB TO YCbCr 4.2.2 :"))
        self.function.setTabText(self.function.indexOf(self.tab4), _translate("YONGATEK", "YCbCr"))
        self.label_10.setText(_translate("YONGATEK", "HEXADECİMAL NUMBER:"))
        self.label_12.setText(_translate("YONGATEK", "HEXADECİMAL NUMBER:"))
        self.label_11.setText(_translate("YONGATEK", "BİNARY NUMBER:"))
        self.BTN_BN2HEX.setText(_translate("YONGATEK", "CONVERT"))
        self.label_9.setText(_translate("YONGATEK", "BİNARY NUMBER:"))
        self.BTN_HEX2BN.setText(_translate("YONGATEK", "CONVERT"))
        self.function.setTabText(self.function.indexOf(self.tab5), _translate("YONGATEK", "BINARY2HEXA"))
        self.label_13.setText(_translate("YONGATEK", "DECİMAL NUMBER:"))
        self.BTN_DEC2BN.setText(_translate("YONGATEK", "CONVERT"))
        self.label_16.setText(_translate("YONGATEK", "BİNARY NUMBER:"))
        self.BTN_BN2DEC.setText(_translate("YONGATEK", "CONVERT"))
        self.label_15.setText(_translate("YONGATEK", "DECİMAL NUMBER:"))
        self.label_14.setText(_translate("YONGATEK", "BİNARY NUMBER:"))
        self.function.setTabText(self.function.indexOf(self.tab6), _translate("YONGATEK", "DECIMAL2BINARY"))
        self.label_29.setText(_translate("YONGATEK", "HEXADECİMAL NUMBER:"))
        self.label_26.setText(_translate("YONGATEK", "DECİMAL NUMBER:"))
        self.BTN_DEC2HEX.setText(_translate("YONGATEK", "CONVERT"))
        self.BTN_HEX2DEC.setText(_translate("YONGATEK", "CONVERT"))
        self.label_27.setText(_translate("YONGATEK", "HEXADECİMAL NUMBER:"))
        self.label_28.setText(_translate("YONGATEK", "DECİMAL NUMBER:"))
        self.function.setTabText(self.function.indexOf(self.tab7), _translate("YONGATEK", "DECIMAL2HEX"))
import icons_rc
